FROM node:24-alpine AS base
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .

FROM base AS dev
CMD [ "npm", "run", "web" ]

FROM base AS build
RUN npm run export:web

FROM nginxinc/nginx-unprivileged:alpine3.23 AS final
COPY --from=build /app/dist /usr/share/nginx/html